version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  # Use underscores instead of joined words
  typescript = true
  tsconfig_path = "./tsconfig.json"
  jsx_framework = "react"

[[transformers]]
name = "prettier"
enabled = true